name: Migrations - liquibase
on: 
  push:  
    branches: 
      - master
    paths:
      - 'liquibase/migrations/changes/*'
  pull_request:
    branches: 
      - master
    paths:
      - 'liquibase/migrations/changes/*'
  workflow_dispatch:

env:
  BASE_DIR: liquibase
  DATABASE: teste-db

jobs:
  calling-migration-local:
        name: Call Migrate - Local
        uses: fabianofm1975/liquibase/.github/workflows/run-local-migration.yml@master
        with:
          BASE_DIR: ${{ BASE_DIR }}

  calling-migration-stg:
        needs: calling-migration-local
        name: Call Migrate - STG
        uses: fabianofm1975/liquibase/.github/workflows/run-db-migration.yml@master
        with:
          ENVIRONMENT: ${{ DATABASE }}-stg
          BASE_DIR: ${{ BASE_DIR }}
        secrets: inherit

  calling-migration-prd:
        needs: calling-migration-stg
        name: Call Migrate - PRD
        uses: fabianofm1975/liquibase/.github/workflows/run-db-migration.yml@master
        with:
          ENVIRONMENT: ${{ DATABASE }}-prd
          BASE_DIR: ${{ BASE_DIR }}
        secrets: inherit







