name: Migrations - liquibase
on: 
  pull_request:
    types: [opened,closed]
    branches: 
      - master
    paths:
      - 'liquibase/migrations/changes/*'

  workflow_dispatch:

jobs:
  calling-migration-local:
        name: Call Migrate - Local
        uses: fabianofm1975/liquibase/.github/workflows/run-local-migration.yml@master
        with:
          ENVIRONMENT: teste-db-stg

  calling-migration-stg:
        if: github.event.pull_request.merged == true
        needs: calling-migration-local
        name: Call Migrate - STG
        uses: fabianofm1975/liquibase/.github/workflows/run-db-migration.yml@master
        with:
          ENVIRONMENT: teste-db-stg
        secrets: inherit

  calling-migration-prd:
        if: github.event.pull_request.merged == true
        needs: calling-migration-stg
        name: Call Migrate - PRD
        uses: fabianofm1975/liquibase/.github/workflows/run-db-migration.yml@master
        with:
          ENVIRONMENT: teste-db-prd
        secrets: inherit
