name: Run Local Migrations
on: 
  workflow_call:
    inputs:
      BASE_FOLDER:
        description: Database base folder
        required: true
        type: string
      ENVIRONMENT:
        description: Environment from which the variables will be set
        required: true
        type: string

jobs:
  local-migrations:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Liquibase Update Action
        uses: liquibase-github-actions/update@v4.21.1
        with:
          changelogFile: "${{ vars.POSTGRES_DATABASE }}/migrations/changes/postgres.changelog.sql"
          url: "jdbc:postgresql://${{ vars.POSTGRES_HOST }}:${{ vars.POSTGRES_PORT }}/${{ vars.POSTGRES_DATABASE }};"
          password: "${{ secrets.POSTGRES_PASSWORD }}"
          rollbackOnError: "true"
          showSummary: "VERBOSE"
          username: "${{ vars.POSTGRES_USER }}"

      #- name: Liquibase Rollback Action
      #  uses: liquibase-github-actions/rollback@v4.21.1
      #  with:
      #    changelogFile: "${{ vars.POSTGRES_DATABASE }}/migrations/changes/postgres.changelog.sql"
      #    url: "jdbc:postgresql://${{ vars.POSTGRES_HOST }}:${{ vars.POSTGRES_PORT }}/${{ vars.POSTGRES_DATABASE }};"
      #    password: "${{ secrets.POSTGRES_PASSWORD }}"
      #    showSummary: "VERBOSE"
      #    username: "${{ vars.POSTGRES_USER }}"
