name: Run Local Migrations
on: 
  workflow_call:
    inputs:
      BASE_DIR:
        description: Folder where to find the changelog file
        required: true
        type: string

jobs:
  local-migrations:
    name: postgres
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports: 
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s
          --health-timeout 5s 
          --health-retries 20
  
  liquibase:
    name: liquibase
    runs-on: ubuntu-latest
    needs: postgres
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Liquibase Update Action
        uses: liquibase-github-actions/update@v4.21.1
        with:            
            changelogFile: "${{ inputs.BASE_DIR }}/migrations/changelog.xml"  
            showSummary: "VERBOSE"
            url: "jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgres"
