name: Run DB Migrations
on: 
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: Environment from which the variables will be set
        required: true
        type: string

jobs:
  liquibase:
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    name: Run DB Migration - ${{ inputs.ENVIRONMENT }}    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Liquibase Update Action
        uses: liquibase-github-actions/update@v4.21.1
        with:            
          changelogFile: "${{ inputs.BASE_DIR }}/migrations/changelog.xml"  
          showSummary: "VERBOSE"
          username: ${{ vars.POSTGRES_USER }}
          password: ${{ secrets.POSTGRES_PASSWORD }}
          url: jdbc:postgresql://${{ vars.POSTGRES_HOST }}:${{ vars.POSTGRES_PORT }}/${{ vars.POSTGRES_DATABASE }}